library(e1071)
srd1 <- read.csv("srd1.csv", header=FALSE)
srd2 <- read.csv("srd2.csv", header=FALSE)
y1 <- rep(0,1000)
y2 <- rep(1,1000)
y <- factor(c(y1,y2))
x <- rbind(srd1,srd2)
model <- svm(x,y,type="C-classification")
p <-predict(model,x)
plot(array(p))
f = plot(srd1, col="red")
points(srd2, col="blue")
library(scatterplot3d)
i<-as.matrix(as.numeric(predict(model, x[1 : 1000, ])) -1)
j<-as.matrix(as.numeric(predict(model, x[1001 : 2000, ]))) -2
j<-abs(j)
z<-c(i, j)
scatterplot3d(x[,1], x[,2], z, pch=1, highlight.3d=TRUE, type="h", 
main="SVM_2", xlab = "x", ylab = "y", zlab = "ambiguity", angle = 65)